myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    ]

news/urls.py
from django.urls import path
from . import views

app_name = "news"
urlpatterns = [
    path('', views.index, name="index"),
    path('chart/', views.chart, name="chart"),
    path('chart01/', views.chart_01, name="chart01"),
    path('add/', views.add_post, name="add"),
    path('save/', views.save_news, name="save"),
    path('addbb/', views.add_baby, name="addbb"),
    path('savebb/', views.save_baby, name="savebb"),
    path('addks/', views.add_khaosat, name="addks"),
    path('saveks/', views.save_khaosat, name="saveks"),
    path('viewks/', views.view_khaosat, name="viewks"),
    path('viewch/', views.chuanhoa, name="viewch"),
    path('viewdes/', views.view_describe, name="viewdes"),
    path('chrt/', views.chart_select_view, name="chrt"),
]

news/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    content = models.TextField(max_length=1000, blank=False, null=False)
    time_create = models.DateTimeField(default=timezone.datetime.now())


class Baby(models.Model):
    age = models.IntegerField(default=0)
    weight = models.IntegerField(default=0)


# Create your models here.
Dia_Ban = [
    (1, "Đồng bằng"), (2, "Ven biển"),
    (3, "Trung du"), (4, "Miền núi – hải đảo"),
]

Gioi_Tinh = [(0, "Nữ"), (1, "Nam"), ]

Dan_Toc = [(0, "Kinh"), (1, "Khác"), ]

Hoc_Van = [(1, "Chưa đi học"), (2, "Tiểu học"), (3, "THCS"), (4, "THPT - BTPT"), ]

Quyen_QD =[ (1, "Không có quyền ra quyết định"),
            (2, "Cùng ra quyết định với một người khác không phải là thành viên gia đình"),
            (3, "Cùng ra quyết định với một thành viên trong gia đình"),
            (4, "Vợ chồng cùng ra quyết định"),
            (5, "Tự mình ra quyết định"),]

Mucdo_QD = [(1, "Rất không tự tin"),
            (2, "Không tự tin"),
            (3, "Bình thường"),
            (4, "Khá tự tin"),
            (5, "Rất tự tin"),]

Quyen_SH = [ (1, "Không có quyền ra sở hữu"),
            (2, "Cùng sở hữu với một người khác không phải là thành viên gia đình"),
            (3, "Cùng sở hữu với một thành viên trong gia đình"),
            (4, "Vợ chồng cùng sở hữu"),
            (5, "Sở hữu một mình"),]



class Khaosat(models.Model):
    dienthoai = models.CharField(max_length=15)
    thon = models.CharField(max_length=50)
    xa = models.CharField(max_length=50)
    huyen = models.CharField(max_length=50)
    tinh = models.CharField(max_length=50)
    diaban = models.IntegerField(default=1, choices=Dia_Ban)
    gioitinh = models.IntegerField(default=0, choices=Gioi_Tinh)
    dantoc = models.IntegerField(default=0, choices=Dan_Toc)
    tuoi = models.IntegerField(default=0)
    hocvan = models.IntegerField(default=1, choices=Hoc_Van)
    cau1a1 = models.IntegerField(default=1, choices=Quyen_QD)
    cau1a2 = models.IntegerField(default=1, choices=Mucdo_QD)
    cau1b1 = models.IntegerField(default=1, choices=Quyen_QD)
    cau1b2 = models.IntegerField(default=1, choices=Mucdo_QD)
    cau1c1 = models.IntegerField(default=1, choices=Quyen_QD)
    cau1c2 = models.IntegerField(default=1, choices=Mucdo_QD)
    cau2a = models.IntegerField(default=1, choices=Quyen_SH)
    cau2b = models.IntegerField( default=1, choices=Quyen_SH)
    

news/forms.py
from django import forms
from .models import Post, Baby, Khaosat


class Post_Form(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','content')


class Baby_Form(forms.ModelForm):
    class Meta:
        model = Baby
        fields = ('age','weight')


class Khaosat_Form(forms.ModelForm):
    class Meta:
        model = Khaosat
        fields = '__all__'

news/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import Post_Form, Baby_Form, Khaosat_Form
from .models import Baby, Khaosat
from .utils import get_simple_plot
import json
import pandas as pd

# Create your views here.
def index(request):
    return render(request, "news/index.html")

# Create your views here.
def chart_01(request):
    return render(request, "news/chart01.html")

# Create your views here.
def chart_select_view( request): 
    graph = None 
    error_message=None 
    df = None 
    khaosat_df = pd.DataFrame(Khaosat.objects.all().values()) 

    if khaosat_df.shape[0] > 0: 
        if request.method == 'POST': 
            chart_type = request.POST.get('style') 
            #diaban = request.POST['diaban'] 
            nut = request.POST['nut'] 
            
            #print("Dia ban :", diaban, ' : Nút bấm :', nut)            
            #date_to = request.POST['date_to'] 
            #print(chart_type) 
            if chart_type != "": 
                #df1 = khaosat_df['gioitinh'].describe()
                df1 = khaosat_df.groupby('hocvan')
                print(df1.describe()['tuoi'])
                
                # function to get a graph 
                graph = get_simple_plot(chart_type, x=khaosat_df['gioitinh'], y=khaosat_df['hocvan'], data=khaosat_df) 
            else: 
                error_message = 'Please select a chart type to continue' 
        else: 
            error_message = "No records in the database"

    context = {
        'graph' : graph,
        'error_message': error_message, 
        }
    if nut =='1':
        return render(request, 'news/chrt.html', context)
    else:
        return chart(request)    





# Create your views here.
def view_describe(request): 
    df = None 
    khaosat_df = pd.DataFrame(Khaosat.objects.all().values()) 

    if khaosat_df.shape[0] > 0: 
        if request.method == 'GET': 
            df1 = khaosat_df.groupby('hocvan')
            data =df1['gioitinh'].describe()
            #print(data)
            title = "Mô tả dữ liệu giữa Nhóm học vấn và giới tính"
    context = {
        'data' : data,
        'title' : title,
        }
    return render(request, 'news/view_describe.html', context)





def chart(request):
    data_arr = [['tuoi', 'hocvan']]
    for item in Khaosat.objects.all():
        data_arr.append([item.tuoi, item.hocvan])
        #print(data_arr)
    return render(request,'news/chart.html',{'item':json.dumps(data_arr)})
    #json.dumps(data_arr)


def add_post(request):
    a = Post_Form()
    return render(request, "news/add_news.html", {'f': a})

def save_news(request):
    if request.method == "POST":
        g = Post_Form(request.POST)
        if g.is_valid():
            g.save()
            return HttpResponse("Luu OK")
        else:
            return HttpResponse("Loi du lieu")
    else:
        return HttpResponse("Khong phai POST request")


def add_baby(request):
    f = Baby_Form()
    return render(request, "news/add_Baby.html", {'form': f})


def save_baby(request):
    if request.method == "POST":
        g = Baby_Form(request.POST)
        if g.is_valid():
            g.save()
            return HttpResponse("Luu Baby OK")
        else:
            return HttpResponse("Loi du lieu")
    else:
        return HttpResponse("Khong phai POST request")

def add_khaosat(request):
    a = Khaosat_Form()
    return render(request, "news/add_khaosat.html", {'f': a})


def save_khaosat(request):
    if request.method == "POST":
        g = Khaosat_Form(request.POST)
        #print(g)
        if g.is_valid():
            g.save()
            return view_khaosat(request) #render(request, "news/view_khaosat.html")
        else:
            return HttpResponse("Loi du lieu")
    else:
        return HttpResponse("Khong phai POST request")


def view_khaosat(request):
    ks = Khaosat.objects.all().values() #values_list
    df = pd.DataFrame(ks)
    df = df.reset_index().to_json(orient ='records')
    #df1 = df.describe()
    #print(df['hocvan'].describe())
    data = []
    data = json.loads(df)
    context ={
        'khaosat': data,
        #'describe': df1.to_html(),
    }
    return render(request, "news/view_khaosat.html", context)


# Create your views here.
def chuanhoa(request):
    return render(request, "news/chuanhoa.html")

news/templates/news/Chart02.html
<html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Task', 'Hours per Day'],
          ['Work',     11],
          ['Eat',      2],
          ['Commute',  2],
          ['Watch TV', 2],
          ['Sleep',    7]
        ]);

        var options = {
          title: 'My Daily Activities',
          is3D: true,
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="piechart_3d" style="width: 900px; height: 500px;"></div>
  </body>
</html>

news/templates/news/add_Baby.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cập nhật tin bài</title>
</head>
<body>
    <form action="{% url 'news:savebb' %}" method="post">
    {% csrf_token %}
            <table>
            <tr>
                <th>
                    <label for="{{ form.age.id_for_age }}">Tuổi:</label>
                </th>
                <td>
                    {{ form.age }}
                <td>
            </tr>
            <tr>
                <th>
                    <label for="{{ form.weight.id_for_weight }}">Cân nặng:</label>
                </th>
               <td>
                    {{ form.weight }}
               </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Thêm">
                </td>
            </tr>
    </table>
    </form>
</body>
</html>

news/templates/news/add_khaosat.html
{% extends 'news/index.html' %}
{% block content %}

 <form action="{% url 'news:saveks' %}" method="post">
    {% csrf_token %}
            <table class="ui celled table">
            <tr>
                <th colspan="2">
                    <label for="{{ f.dienthoai.id_for_dienthoai }}">Điện thoại:</label>
                </th>
                <td>
                    {{ f.dienthoai }}
                <td>
                <td></td>    
            </tr>
            <tr>
                <th colspan="2">
                    <label for="{{ f.thon.id_for_thon }}">Thôn:</label>
                </th>
               <td>
                    {{ f.thon }}
               </td>
               <td></td>
            </tr>
            <tr>
                <th colspan="2">
                    <label for="{{ f.xa.id_for_xa }}">Xã:</label>
                </th>
               <td>
                    {{ f.xa }}
               </td>
               <td></td>
            </tr>
                <tr>
                <th colspan="2">
                    <label for="{{ f.huyen.id_for_huyen }}">Huyện:</label>
                </th>
               <td>
                    {{ f.huyen }}
               </td>
               <td></td>
            </tr>
            <tr>
                <th colspan="2">
                    <label for="{{ f.tinh.id_for_tinh }}">Tỉnh:</label>
                </th>
               <td>
                    {{ f.tinh }}
               </td>
               <td></td>
            </tr>
            <tr>
                <th colspan="2">
                    <label for="{{ f.diaban.id_for_diaban }}">Địa bàn:</label>
                </th>
               <td>
                    {{ f.diaban }}
               </td>
               <td></td>
            </tr>
            <tr>
                <th colspan="2">
                    <label for="{{ f.gioitinh.id_for_gioitinh }}">Giới tính:</label>
                </th>
               <td>
                    {{ f.gioitinh }}
               </td>
               <td></td>
            </tr>
            <tr>
                <th colspan="2">
                    <label for="{{ f.dantoc.id_for_dantoc }}">Dân tộc:</label>
                </th>
               <td>
                    {{ f.dantoc }}
               </td>
               <td></td>
            </tr>
            <tr>
                <th colspan="2">
                    <label for="{{ f.tuoi.id_for_tuoi }}">Tuổi:</label>
                </th>
               <td>
                    {{ f.tuoi }}
               </td>
               <td></td>
            </tr>
            <tr>
                <th colspan="2"> 
                    <label for="{{ f.hocvan.id_for_hocvan }}">Học vấn:</label>
                </th>
               <td>
                    {{ f.hocvan }}
               </td>
               <td></td>
            </tr>

            <tr>
                <th colspan="4">
                    <p align="center">1.  THAM GIA SẢN XUẤT </p>                  
                </th>
            </tr>    
            <tr>
                <th colspan="4">
                <p>Mục này  gồm các câu hỏi về hai nội dung: (1)  tham gia vào các hoạt động nông nghiệp và (2) việc ra quyết định về các vấn đề khác nhau của trong đời sống gia đình. </p>
                <th>
            </tr>

            <tr>
                <td></td>
                <td></td>
                <td>Việc ra quyết định cho các hoạt động dưới  đây thường được thực hiện cùng với ai?</td>
                <td>Mức độ tự tin mà cá nhân cảm thấy có thể  ra quyết định cho các hoạt động ?</td>
            </tr>
            <tr>

            <tr>
                <td>A</td>
                <th>
                    <label for="{{ f.cau1a1.id_for_cau1a1 }}">Trồng cây lương thực: (các loại cây trồng phục vụ chủ yếu cho nhu cầu sử dụng của gia đình):
                    </label>
                </th>

                <td>
                    {{ f.cau1a1 }}
               </td>
                <td>
                    <label for="{{ f.cau1a1.id_for_cau1a2 }}"></label>
                    {{ f.cau1a2 }}
               </td>
            </tr>

            <tr>
                <td>B</td>
                <th>
                    <label for="{{ f.cau1a1.id_for_cau1a1 }}">Trồng cây thương mại: (các loại cây trồng mà sản phẩm sau thu hoạch có thể buôn bán):
                    </label>
                </th>

                <td>
                    {{ f.cau1b1 }}
               </td>
                <td>
                    <label for="{{ f.cau1a1.id_for_cau1b2 }}"></label>
                    {{ f.cau1b2 }}
               </td>
            </tr>

            <tr>
                <td>C</td>
                <th>
                    <label for="{{ f.cau1a1.id_for_cau1a1 }}">Hoạt động chăn nuôi:
                    </label>
                </th>

                <td>
                    {{ f.cau1c1 }}
               </td>
                <td>
                    <label for="{{ f.cau1a1.id_for_cau1c2 }}"></label>
                    {{ f.cau1c2 }}
               </td>
            </tr>

            <tr>
                <td>2A</td>
                <th>
                    <label for="{{ f.cau2a.id_for_cau2a }}">Đất nông nghiệp (thửa/mảnh):
                    </label>
                </th>
                <td colspan="2">
                    {{ f.cau2a }}
               </td>
            </tr>

            <tr>
                <td>2B</td>
                <th>
                    <label for="{{ f.cau2b.id_for_cau2b }}">Vật nuôi lớn (gia súc, gia cầm…):
                    </label>
                </th>
                <td colspan="2">
                    {{ f.cau2b }}
               </td>
            </tr>

            <tr>
                <td></td><td></td>
                <td >
                    <input type="submit" value="Thêm">
                </td>
                <td></td>
            </tr>
    </table>
    </form>
{% endblock %}

news/templates/news/add_news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cập nhật tin bài</title>
</head>
<body>
    <form action="{% url 'news:save' %}" method="post">
    {% csrf_token %}
            <table>
            <tr>
                <th>
                    <label for="{{ f.title.id_for_title }}">Tiêu đề:</label>
                </th>
                <td>
                    {{ f.title }}
                <td>
            </tr>
            <tr>
                <th>
                    <label for="{{ f.content.id_for_content }}">Nội dung:</label>
                </th>
               <td>
                    {{ f.content }}
               </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Thêm">
                </td>
            </tr>
    </table>
    </form>
</body>
</html>

news/templates/news/chart.html
 {% extends 'news/index.html' %}
 {% block content %}

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable(
          {{item|safe}}
          );
        <!-- Đây là dòng chú thích trong html -->
        var options = {
          title: 'Tuổi vs. Học vấn comparison',
          hAxis: {title: 'Tuổi', minValue: 0, maxValue: 100},
          vAxis: {title: 'Học vấn', minValue: 0, maxValue: 5},
          legend: 'none'
        };

        var chart = new google.visualization.ScatterChart(document.getElementById('chart_div'));

        chart.draw(data, options);
      }
    </script>
    {% csrf_token %}
    <div id="chart_div" style="width: 900px; height: 500px;"></div>
{% endblock %} 

news/templates/news/chrt.html
{% extends 'news/index.html' %}
{% block content %}

  {% if request.POST %} 
    {% if graph %}
      <img src="data: image/png; base64, {{ graph | safe}}">
    {% endif %}
  {% endif %}

{% endblock %}

news/templates/news/chuanhoa.html
{% extends 'news/index.html' %}

{% block content %}
    <h2>Form - Biểu mẫu trong CSS</h2>
      <h5>Quách Tỉnh, 14/02/2019</h5>
      <div class="fakeimg" style="height:200px;">Ảnh</div>
      <p>Form là một phần không thể thiếu trong bất kì loại website nào. </p>
      <p>Ở bài viết này, Quantrimang.com sẽ hướng dẫn bạn cách xây dựng phần 
      giao diện hiển thị của một biểu mẫu cơ bản. Giao diện này có thể được làm
      khá đẹp mắt với CSS</p>

{% endblock %}

news/templates/news/index.html
<!DOCTYPE html>
<html>
<head>
  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" />
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.6/semantic.min.css">
  <link rel="text/javascript" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.6/semantic.min.js">
  <style>
      h1 {
          text-align: center;
          color: orange;
      }
  </style>

<style>
* {
  box-sizing: border-box;
}

body {
  font-family: Verdana; /* Arial --> */
  padding: 10px;
  background: #e9d8f4;
}

/* Header/Blog Title */
.header {
  padding: 10px;
  text-align: center;
  background: white;
  color: #58257b;
}

.header h1 {
  font-size: 40px;
}

.header p {
  font-size: 20px;
}

/* Style the top navigation bar */
.topnav {
  overflow: hidden;
  background-color: #58257b;
}

/* Định dạng link điều hướng */
.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

/* Thay đổi màu liên kết khi di chuột qua */
.topnav a:hover {
  background-color: #db7093;
  color: white;
}

/* Tạo hai cột không bằng nhau, float cạnh nhau */
/* Cột trái */
.leftcolumn { 
  float: left;
  width: 75%;
}

/* Cột phải */
.rightcolumn {
  float: left;
  width: 25%;
  background-color: #e9d8f4;
  padding-left: 20px;
}

/* Hình ảnh tượng trưng */
.fakeimg {
  background-color: #baa1cc;
  width: 100%;
  padding: 0px;
}

/* Thêm định dạng thẻ cho bài viết */
.card {
  background-color: white;
  padding: 20px;
  margin-top: 20px;
}

/* Clear float khác sau các cột */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Footer */
.footer {
  padding: 10px;
  text-align: center;
  background: white;
  margin-top: 10px;
}

/* Bố cục linh hoạt: các cột xếp chồng lên nhau thay vì cạnh nhau khi màn hình 
có chiều rộng dưới 700px */
@media screen and (max-width: 700px) {
  .leftcolumn, .rightcolumn { 
    width: 100%;
    padding: 0;
  }
}

/* Bố cục linh hoạt: Thanh menu điều hướng xếp chồng lên nhau thay vì cạnh nhau
khi màn hình có chiều rộng dưới 300px */
@media screen and (max-width: 300px) {
  .topnav a {
    float: none;
    width: 100%;
  }
} 
</style>
</head>
<body>

<div class="header">
  <h1>HỆ THỐNG PHÂN TÍCH DỮ LIỆU VÀ DỰ BÁO</h1>
  <p>Kiến thức - Kinh nghiệm - Trung thực - Hiệu quả</p>
</div>
<div class="topnav">
  <a href="{% url 'news:addks' %}">Thu thập dữ liệu</a>
  <a href="{% url 'news:viewks' %}">Kết quả khảo sát</a>
  <a href="{% url 'news:viewdes' %}">Chuẩn hóa dữ liệu</a>
  <a href="{% url 'news:index' %}">Phân tích dữ liệu</a>
  <a href="{% url 'news:chart01' %}">Mô hình Dự báo</a>
  <a href="{% url 'news:index' %}">Khuyến nghị</a>
  <a href="{% url 'news:index' %}" style="float:right">Đăng nhập</a>
  <a href="{% url 'news:index' %}" style="float:right">Đăng ký</a>
</div>

<div class="row">
  <div class="leftcolumn">
    <div class="card">
      <div class="ui container">
        {% block content %}
        {% endblock content %}
      </div>
    </div>
   
  </div>


  <div class="rightcolumn">
    <div class="card">
      <h2>Giới thiệu</h2>
      <div class="fakeimg" style="height:128px;"><img src="{% static 'news/03.jpg' %}" alt="data science" style="width:100%;height:128px;"></div>
      <p align="center">dainfo.com là trang về khoa học dữ liệu.</p>
    </div>
    <div class="card">
      <h3>Nổi bật</h3>
      <div class="fakeimg" style="height:128px;"><p><img src="{% static 'news/03.jpg' %}" alt="data science" style="width:100%;height:128px;"></p></div>
      <div class="fakeimg" style="height:128px;"><p><img src="{% static 'news/03.jpg' %}" alt="data science" style="width:100%;height:128px;"></p></div>
    </div>
    <div class="card">
      <h3>Follow Me</h3>
      <p>Facebook</p>
      <p>YouTube</p>
    </div>
  </div>
</div>

<div class="footer">
  <h4>Giấy phép số 000/GP-BTTTT. Bộ TT&TT cấp ngày 30/09/2021.</h4>
</div>

</body>
</html>

news/templates/news/index01.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>27</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" />
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.6/semantic.min.css">
  <link rel="text/javascript" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.6/semantic.min.js">
  <style>
      h1 {
          text-align: center;
      }
  </style>
</head>
<body>
<h1><a class="ui red label">HỆ THỐNG PHÂN TÍCH VÀ DỰ BÁO </a> </h1>
<hr />
<div id="tabs" >
  <ul>
    <li><a href="{% url 'news:addks' %}"><span>Thu thập dữ liệu</span></a></li>
    <li><a href="{% url 'news:viewks' %}"><span>Kết quả thu thập</span></a></li>
    <li><a href="{% url 'news:index' %}"><span>Chuẩn hóa Dữ liệu</span></a></li>
    <li><a href="{% url 'news:index' %}"><span>Phân tích Dữ liệu</span></a></li>
    <li><a href="{% url 'news:index' %}"><span>Mô hình Dự báo</span></a></li>
    <li><a href="{% url 'news:index' %}"><span>Khuyến nghị </span></a></li>
    <li><a rel="nofollow" target="_blank" href="{% url 'news:index' %}" title="explodingboy"><span>explodingboy</span></a></li>
  </ul>
</div>
</body>
</html>

news/templates/news/view_khaosat.html
{% extends 'news/index.html' %}
{% block content %}
<div style="overflow:auto;">
    <table class="ui single line celled unstackable bottom attached table">
      <thead>
        <tr><th>Mã ID</th>
        <th>Điện thoại</th>
        <th>Thôn</th>
        <th>Xã</th>
        <th>Huyện</th>
        <th>Tỉnh</th>
        <th>Địa bàn</th>
        <th>Giới tính</th>
        <th>Dân tộc</th>
        <th>Tuỏi</th>
        <th>Học vấn</th>
        <th>Câu 1 a 1</th>
        <th>Câu 1 a 2</th>
        <th>Câu 1 b 1</th>
        <th>Câu 1 b 2</th>
        <th>Câu 1 c 1</th>
        <th>Câu 1 c 2</th>
        <th>Câu 2 a</th>
        <th>Câu 2 b</th>

      </tr></thead>
      <tbody>
        {% if khaosat %}  
        {% for i in khaosat %}
        <tr>
          <th>{{ i.id }}</th>
          <th>{{ i.dienthoai }}</th>
          <th>{{ i.thon }}</th>
          <th>{{ i.xa }}</th>
          <th>{{ i.huyen }}</th>
          <th>{{ i.tinh }}</th>
          <th>{{ i.diaban }}</th>
          <th>{{ i.gioitinh }}</th>
          <th>{{ i.dantoc }}</th>
          <th>{{ i.tuoi }}</th>
          <th>{{ i.hocvan }}</th>
          <th>{{ i.cau1a1 }}</th>
          <th>{{ i.cau1a2 }}</th>
          <th>{{ i.cau1b1 }}</th>
          <th>{{ i.cau1b2 }}</th>
          <th>{{ i.cau1c1 }}</th>
          <th>{{ i.cau1c2 }}</th>
          <th>{{ i.cau2a }}</th>
          <th>{{ i.cau2b }}</th>
        </tr>
        {% endfor %}
        {% endif %}
      </tbody>
    </table>
</div>


    <form action="{% url 'news:chrt' %}" method="post" class="ui form">
        {% csrf_token %}
      <table>  
        <tr>
        <th>
        <input type="hidden" name="style" value="khac">
        <button class="ui primary button" name= "nut" value='1'>
        Biểu đồ Giới tính và Học vấn
        </button>
        </th>
        <th>
        <button class="ui primary button" name= "nut" value='2'>
        Biểu đồ Tuổi và Học vấn
        </button>
        </th>
      </tr>
      </tr>
      </table>    
    </form>


{% endblock %}